### ISSUE TITLE
[SPEC] Change "services" to "components", to be more C4-like

### ISSUE THREAD

**Issue by mtfuller** [ArchDoc/archdoc-ui#2]
Currently, the ArchDoc spec outlines two major contracts: users and services. The 'service' construct refers to microservices or apps that exist within your architecture. However, I feel we want to rename the term "service" to "component" to be more general. Components can be APIs, databases, storage buckets, etc. Another advantage of components is that it adheres to the C4 architecture framework terminology.

### Examples
Instead of the following ArchDoc spec:
```yaml
services:
  api:
    description: The API gateway of the application.
    repository: https://github.com/MyOrg/api-gateway
    tags:
      - backend
      - public
```
We will be using the following:
```yaml
components:
  api:
    description: The API gateway of the application.
    repository: https://github.com/MyOrg/api-gateway
    tags:
      - backend
      - public
```

Acceptance Criteria
- ArchDoc UI parses ArchDoc spec files so that the services is renamed to components
- All ArchDoc UI tests are modified to reflect this
- All ArchDoc spec examples are updated to the latest schema
